name: Test and create PR
on:
  push:
    branches: 'part-*'

jobs:

  test:
    name: Maven test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven test
      run: mvn -B test --file pom.xml

  get-ref-branch-name:
    name: Get ref branch name
    runs-on: ubuntu-latest
    env:
      GITHUB_BRANCH: ${{ github.ref }}
    steps:
    - name: Get only the name
      run: |
        echo "::set-output name=ref_branch::${GITHUB_BRANCH#refs/heads/}"

  set-destination-branch:
    name: Set destination branch
    needs: test
    runs-on: ubuntu-latest
    outputs:
      dest_branch: ${{ env.DEST_BRANCH }}
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: If branch is part-1
      if: contains(github.ref, 'part-1')
      run: |
        echo "::set-env name=DEST_BRANCH::part-2-two"
    - name: If branch is part-2
      if: contains(github.ref, 'part-2')
      run: |
        echo "::set-env name=DEST_BRANCH::part-3-three"
    - name: check DEST_BRANCH
      run: echo "$DEST_BRANCH"

  create-pull-request:
    name: Create pull request
    needs:
      - get-ref-branch-name
      - set-destination-branch
    runs-on: ubuntu-latest
    steps:
    - name: Generate app token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Dump needs context
      env:
        NEEDS_CONTEXT: ${{ toJson(needs) }}
      run: echo "$NEEDS_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.set-destination-branch.outputs.dest_branch }}  
    - name: Reset promotion branch
      run: |
        git fetch origin ${{ github.ref }}:${{ github.ref }}
        git reset --hard ${{ github.ref }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        branch: temp-promotion-branch
        title: "Pulling ${{ github.ref }} into ${{ needs.set-destination-branch.outputs.dest_branch }}"
        body: "Update from ${{ github.ref }} :robot: auto-generated"
        commit-message: "Update from ${{ github.ref }}"
        labels: auto-pr, auto-merge
